name: PandaNewCore
main: me.zpandakst.Main
version: 2.5.8
description: Plugin CORE novo das redes de teste Panda
author: zPandaKST_
commands:
  cc:
  chatclear:
  setcargo:
  changegroup:
  pentcheck:
  account:
  fly:
  voar:
  forcechat:
  setspawn:
  spawn:
  groupset:
  resetaccount:
  resetallaccounts:
  checkkey:
  setvip:
  getconfig: